### PR TITLE
Cu 86ctu7vda implement module entry hans duran

### PR DESCRIPTION
**Pull request by HoneyHanny**
Add UI for Menu and Upload

### CODE REVIEW

**Comment by kaimatzu** [comment]
Task linked: [CU-86ctu7vda [Implement Module] Entry](https://app.clickup.com/t/86ctu7vda)

**Comment by HoneyHanny** [comment]
Merge conflicts fixed

**Comment by HoneyHanny** [comment]
char murag true

**Review by kaimatzu — APPROVED** [review]
good

**Pull request merged**
